# Generated by Django 3.2.6 on 2021-10-08 19:37

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_attendance', models.CharField(default='', max_length=32, verbose_name='id_atendimento')),
                ('cpf', models.CharField(max_length=11)),
                ('session', models.TextField(blank=True, default='', verbose_name='sessao')),
                ('intent', models.TextField(blank=True, default='', verbose_name='intencao')),
                ('confidance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='grau_confianca_intencao')),
                ('source', models.CharField(default='', max_length=32, verbose_name='fonte')),
                ('channel', models.CharField(default='', max_length=32, verbose_name='canal')),
                ('id_node', models.TextField(blank=True, default='', verbose_name='id_no')),
                ('step', models.CharField(default='opened', max_length=15, verbose_name='status')),
                ('longitude', models.DecimalField(decimal_places=16, default=0, max_digits=22)),
                ('latitude', models.DecimalField(decimal_places=16, default=0, max_digits=22)),
                ('protocol', models.TextField(blank=True, default='', verbose_name='protocolo')),
                ('ip', models.CharField(max_length=15)),
                ('token', models.CharField(blank=True, default='', max_length=64)),
                ('id_citizen', models.IntegerField(blank=True, null=True, verbose_name='id_cidadao')),
            ],
            options={
                'verbose_name': 'atendimento',
                'verbose_name_plural': 'atendimentos',
            },
        ),
        migrations.CreateModel(
            name='BulkClassifyResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_bulk', models.IntegerField(primary_key=True, serialize=False)),
                ('session', models.TextField(blank=True, default='', verbose_name='sessao')),
                ('question', models.TextField(blank=True, default='', verbose_name='pergunta_usr')),
                ('answer', models.TextField(blank=True, default='', verbose_name='resposta_watson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('channel', models.CharField(default='', max_length=64, verbose_name='canal')),
                ('code', models.CharField(max_length=3, verbose_name='cd_canal')),
            ],
            options={
                'verbose_name': 'canal',
                'verbose_name_plural': 'canais',
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_citizen', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('full_name', models.TextField(blank=True, default='', verbose_name='nome_completo')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail')),
                ('nickname', models.TextField(blank=True, default='')),
                ('mobile', models.TextField(blank=True, default='', verbose_name='celular')),
                ('client_id', models.CharField(default=0, max_length=128)),
                ('client_token', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'cidadao',
                'verbose_name_plural': 'cidadaos',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_file', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_attendance', models.IntegerField(default=0, verbose_name='id_atendimnento')),
                ('id_instruction', models.IntegerField(default=0, verbose_name='id_instrução')),
                ('dt_checking', models.DateTimeField(auto_now_add=True, verbose_name='dt_checking')),
                ('is_checking', models.BooleanField(default=True)),
                ('dt_checkout', models.DateTimeField(blank=True, null=True)),
                ('is_checkout', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=True)),
                ('file_name', models.TextField(blank=True, default='', verbose_name='nm_arquivo')),
                ('file_path', models.FilePathField(default=django.core.files.storage.FileSystemStorage(location='media/'), verbose_name='url_arquivo')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='arquivo')),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'arquivo',
                'verbose_name_plural': 'arquivos',
            },
        ),
        migrations.CreateModel(
            name='GuidePost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_guide_post', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_post_guide', models.IntegerField(verbose_name='Id posto guia')),
                ('id_1', models.CharField(default='', max_length=6, null=True)),
                ('id_8', models.IntegerField(null=True)),
                ('id_2', models.IntegerField(null=True)),
                ('id_16', models.IntegerField(null=True)),
                ('description', models.CharField(default='', max_length=64, null=True, verbose_name='Descrição do posto de atendimento')),
                ('address', models.CharField(default='', max_length=256, null=True, verbose_name='Endereço de posto')),
                ('city', models.CharField(default='', max_length=64, verbose_name='Cidade do posto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_post_service', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_service', models.IntegerField(verbose_name='Id serviço')),
                ('id_guide_post', models.IntegerField()),
                ('description', models.CharField(default='', max_length=256, null=True, verbose_name='Descrição do serviço do posto de atendimento')),
                ('id_organ', models.IntegerField(null=True)),
                ('validator_ne', models.BooleanField(null=True)),
                ('validator_s', models.BooleanField(null=True)),
                ('validator_sa', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RangeIntents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('confidance_min', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='grau_confianca_intencao')),
                ('confidance_max', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='grau_confianca_intencao')),
            ],
            options={
                'verbose_name': 'canal_Skill',
                'verbose_name_plural': 'intervalo_intencao',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_recipient', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail')),
                ('service', models.TextField(blank=True, default='', verbose_name='service')),
                ('path', models.TextField(blank=True, default='', verbose_name='path')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_router', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_recipient', models.IntegerField(default=1)),
                ('is_process', models.BooleanField(default=True, verbose_name='eprocesso')),
                ('is_link', models.BooleanField(default=False, verbose_name='elink')),
                ('is_document', models.BooleanField(default=False, verbose_name='edocumento')),
                ('process', models.TextField(blank=True, default='', verbose_name='processo')),
                ('url', models.TextField(blank=True, default='')),
                ('service', models.CharField(default='', max_length=64, verbose_name='fonte')),
                ('documents', models.TextField(blank=True, default='', verbose_name='documentos')),
            ],
            options={
                'verbose_name': 'rota',
                'verbose_name_plural': 'rotas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('service', models.CharField(default='', max_length=128, verbose_name='servico')),
                ('url_serv_prod', models.CharField(default='', max_length=128, verbose_name='url_prod')),
                ('url_serv_homo', models.CharField(default='', max_length=128, verbose_name='url_homo')),
                ('url_auth_prod', models.CharField(default='', max_length=128, verbose_name='url_auth')),
                ('url_auth_homo', models.CharField(default='', max_length=128, verbose_name='url_auth')),
                ('client_secret', models.CharField(default='', max_length=64, verbose_name='client_secret')),
                ('client_id', models.CharField(default='', max_length=64, verbose_name='client_id')),
                ('grant_type', models.CharField(default='', max_length=64, verbose_name='grant_type')),
                ('scope', models.CharField(default='', max_length=256, verbose_name='scope')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_attendance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'config_sistema',
                'verbose_name_plural': 'config_sistema',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skil_name', models.CharField(max_length=10, verbose_name='nm_skill')),
                ('assistant_apikey', models.CharField(default='', max_length=64, verbose_name='assistant_apikey')),
                ('assistant_id', models.CharField(default='', max_length=64, verbose_name='assistant_id')),
                ('assistant_url', models.CharField(default='', max_length=256, verbose_name='assistant_url')),
                ('assistant_version', models.CharField(default='', max_length=32, verbose_name='assistant_version')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_tax_payment', models.BigAutoField(primary_key=True, serialize=False)),
                ('tax_type', models.CharField(default='', max_length=32, verbose_name='Tipo da taxa')),
                ('tax_name', models.CharField(default='', max_length=32, verbose_name='Nome da taxa')),
                ('tax_value', models.FloatField(default=0.0, verbose_name='Valor da taxa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('channel', models.CharField(default='', max_length=10, verbose_name='canal')),
                ('step', models.IntegerField(default=0, verbose_name='step')),
                ('started', models.BooleanField(default=True, verbose_name='ativo')),
                ('id_skil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
            options={
                'verbose_name': 'canal_skill',
                'verbose_name_plural': 'canal_skill',
            },
        ),
    ]
