# Generated by Django 3.2.6 on 2021-11-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='client_id'),
        ),
        migrations.AlterField(
            model_name='service',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='client_secret'),
        ),
        migrations.AlterField(
            model_name='service',
            name='grant_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='grant_type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='scope'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url_auth_homo',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='url_auth'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url_auth_prod',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='url_auth'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url_serv_homo',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='url_homo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url_serv_prod',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='url_prod'),
        ),
    ]
