# Generated by Django 3.2.4 on 2021-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('city_code', models.CharField(default='', max_length=16, verbose_name='código')),
                ('city_name', models.CharField(default='', max_length=128, verbose_name='cidade')),
            ],
            options={
                'verbose_name': 'Código Cidade',
                'verbose_name_plural': 'Códigos Cidades',
            },
        ),
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('country_code', models.CharField(default='', max_length=8, verbose_name='código')),
                ('country_name', models.CharField(default='', max_length=128, verbose_name='país')),
            ],
            options={
                'verbose_name': 'Código País',
                'verbose_name_plural': 'Códigos Paises',
            },
        ),
    ]
