# Generated by Django 3.2.7 on 2021-10-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycode',
            name='country_code',
            field=models.CharField(default='', max_length=64, verbose_name='código'),
        ),
    ]
